### ISSUE TITLE
Roadmap for v0.1.0

### ISSUE THREAD

**Issue by acdenisSK** [serenity-rs/framework#30]
This is a basic roadmap to get the initial release of the new framework up and running.

What needs to be done:
- [ ] Port buckets from the original framework (relevant issues: https://github.com/serenity-rs/framework/issues/9)
- [ ] Implement utilities for creating a help command and provide plain-text and embed help commands out of the box (relevant issues: https://github.com/serenity-rs/framework/issues/10)
- [ ] Allow more complex types in the argument system that cannot work with just a `FromStr` implementation (relevant issues: https://github.com/serenity-rs/framework/issues/24)

What does not have to be, but would be very nice:
- [ ] Implement localisation utilities such that the user can load and use localised text painlessly (relevant issues: https://github.com/serenity-rs/framework/issues/21)
